### ISSUE TITLE
Error creating a playlist via the API

### ISSUE THREAD

**Issue by ZachSaucier** [subsonic/SubSonic-3.0#290]
Hey there. Thanks for making Subsonic! 

When I try to create a playlist via the Python API, I am getting the following error:

```
Traceback (most recent call last):
  File "gmusic_export.py", line 118, in <module>
    if create_playlist(conn, PLAYLIST_NAME, playlistSongs):
  File "gmusic_export.py", line 74, in create_playlist
    playlists=connection.createPlaylist(name=playlistname,songIds=playlistSongs)
  File "/home/zs/.local/lib/python3.8/site-packages/libsonic/connection.py", line 758, in createPlaylist
    res = self._doInfoReq(req)
  File "/home/zs/.local/lib/python3.8/site-packages/libsonic/connection.py", line 2782, in _doInfoReq
    dres = json.loads(res.read().decode('utf-8'))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)
```

I'm guessing the response isn't in JSON format but the spec says it should be. Any idea how to remedy this?

**Comment by ZachSaucier** [comment]
Wrong subsonic, sorry!
